### PR TITLE
Fix Issue #1, Cleaned up variancechecker function

### PR DESCRIPTION
**Pull request by CometS1**
Modified variancechecker to use calculations instead of checks for ease of use, created calculatevariance function for use with variancechecker.

### CODE REVIEW

**Comment by 2hands10fingers** [comment]
Interesting! I'll try testing it out later tonight.

**Comment by CometS1** [comment]
How did it go?

**Comment by 2hands10fingers** [comment]
@CometS1 

Very clean, but as you can see here, the calculations are off from the desired number. 

Result on the left is using your code, and the right is the old code.

**Comment by CometS1** [comment]
Alright, fixed the issue. There was a large gap between 9500 and 100000 that gives 0.095 no matter what the number rounded was (For example, 23025 gives 0.095). The current commit should fix that.

**Comment by 2hands10fingers** [comment]
@CometS1 Beautiful! You've earned this one :)

**Pull request merged**
